# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.20.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.20.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhaodejin/Documents/QData

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhaodejin/Documents/QData

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.20.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.20.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaodejin/Documents/QData/CMakeFiles /Users/zhaodejin/Documents/QData//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaodejin/Documents/QData/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ComputerForQt

# Build rule for target.
ComputerForQt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ComputerForQt
.PHONY : ComputerForQt

# fast build rule for target.
ComputerForQt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/build
.PHONY : ComputerForQt/fast

#=============================================================================
# Target rules for targets named ComputerForQt_autogen

# Build rule for target.
ComputerForQt_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ComputerForQt_autogen
.PHONY : ComputerForQt_autogen

# fast build rule for target.
ComputerForQt_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt_autogen.dir/build.make CMakeFiles/ComputerForQt_autogen.dir/build
.PHONY : ComputerForQt_autogen/fast

ComputerForQt_autogen/mocs_compilation.o: ComputerForQt_autogen/mocs_compilation.cpp.o
.PHONY : ComputerForQt_autogen/mocs_compilation.o

# target to build an object file
ComputerForQt_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/ComputerForQt_autogen/mocs_compilation.cpp.o
.PHONY : ComputerForQt_autogen/mocs_compilation.cpp.o

ComputerForQt_autogen/mocs_compilation.i: ComputerForQt_autogen/mocs_compilation.cpp.i
.PHONY : ComputerForQt_autogen/mocs_compilation.i

# target to preprocess a source file
ComputerForQt_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/ComputerForQt_autogen/mocs_compilation.cpp.i
.PHONY : ComputerForQt_autogen/mocs_compilation.cpp.i

ComputerForQt_autogen/mocs_compilation.s: ComputerForQt_autogen/mocs_compilation.cpp.s
.PHONY : ComputerForQt_autogen/mocs_compilation.s

# target to generate assembly for a file
ComputerForQt_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/ComputerForQt_autogen/mocs_compilation.cpp.s
.PHONY : ComputerForQt_autogen/mocs_compilation.cpp.s

src/DataStruct/ArrayList.o: src/DataStruct/ArrayList.cpp.o
.PHONY : src/DataStruct/ArrayList.o

# target to build an object file
src/DataStruct/ArrayList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayList.cpp.o
.PHONY : src/DataStruct/ArrayList.cpp.o

src/DataStruct/ArrayList.i: src/DataStruct/ArrayList.cpp.i
.PHONY : src/DataStruct/ArrayList.i

# target to preprocess a source file
src/DataStruct/ArrayList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayList.cpp.i
.PHONY : src/DataStruct/ArrayList.cpp.i

src/DataStruct/ArrayList.s: src/DataStruct/ArrayList.cpp.s
.PHONY : src/DataStruct/ArrayList.s

# target to generate assembly for a file
src/DataStruct/ArrayList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayList.cpp.s
.PHONY : src/DataStruct/ArrayList.cpp.s

src/DataStruct/ArrayWindow.o: src/DataStruct/ArrayWindow.cpp.o
.PHONY : src/DataStruct/ArrayWindow.o

# target to build an object file
src/DataStruct/ArrayWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayWindow.cpp.o
.PHONY : src/DataStruct/ArrayWindow.cpp.o

src/DataStruct/ArrayWindow.i: src/DataStruct/ArrayWindow.cpp.i
.PHONY : src/DataStruct/ArrayWindow.i

# target to preprocess a source file
src/DataStruct/ArrayWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayWindow.cpp.i
.PHONY : src/DataStruct/ArrayWindow.cpp.i

src/DataStruct/ArrayWindow.s: src/DataStruct/ArrayWindow.cpp.s
.PHONY : src/DataStruct/ArrayWindow.s

# target to generate assembly for a file
src/DataStruct/ArrayWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/ArrayWindow.cpp.s
.PHONY : src/DataStruct/ArrayWindow.cpp.s

src/DataStruct/DataTable.o: src/DataStruct/DataTable.cpp.o
.PHONY : src/DataStruct/DataTable.o

# target to build an object file
src/DataStruct/DataTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/DataTable.cpp.o
.PHONY : src/DataStruct/DataTable.cpp.o

src/DataStruct/DataTable.i: src/DataStruct/DataTable.cpp.i
.PHONY : src/DataStruct/DataTable.i

# target to preprocess a source file
src/DataStruct/DataTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/DataTable.cpp.i
.PHONY : src/DataStruct/DataTable.cpp.i

src/DataStruct/DataTable.s: src/DataStruct/DataTable.cpp.s
.PHONY : src/DataStruct/DataTable.s

# target to generate assembly for a file
src/DataStruct/DataTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/DataTable.cpp.s
.PHONY : src/DataStruct/DataTable.cpp.s

src/DataStruct/LinkListWindow.o: src/DataStruct/LinkListWindow.cpp.o
.PHONY : src/DataStruct/LinkListWindow.o

# target to build an object file
src/DataStruct/LinkListWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/LinkListWindow.cpp.o
.PHONY : src/DataStruct/LinkListWindow.cpp.o

src/DataStruct/LinkListWindow.i: src/DataStruct/LinkListWindow.cpp.i
.PHONY : src/DataStruct/LinkListWindow.i

# target to preprocess a source file
src/DataStruct/LinkListWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/LinkListWindow.cpp.i
.PHONY : src/DataStruct/LinkListWindow.cpp.i

src/DataStruct/LinkListWindow.s: src/DataStruct/LinkListWindow.cpp.s
.PHONY : src/DataStruct/LinkListWindow.s

# target to generate assembly for a file
src/DataStruct/LinkListWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/LinkListWindow.cpp.s
.PHONY : src/DataStruct/LinkListWindow.cpp.s

src/DataStruct/main.o: src/DataStruct/main.cpp.o
.PHONY : src/DataStruct/main.o

# target to build an object file
src/DataStruct/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/main.cpp.o
.PHONY : src/DataStruct/main.cpp.o

src/DataStruct/main.i: src/DataStruct/main.cpp.i
.PHONY : src/DataStruct/main.i

# target to preprocess a source file
src/DataStruct/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/main.cpp.i
.PHONY : src/DataStruct/main.cpp.i

src/DataStruct/main.s: src/DataStruct/main.cpp.s
.PHONY : src/DataStruct/main.s

# target to generate assembly for a file
src/DataStruct/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/main.cpp.s
.PHONY : src/DataStruct/main.cpp.s

src/DataStruct/pushButton.o: src/DataStruct/pushButton.cpp.o
.PHONY : src/DataStruct/pushButton.o

# target to build an object file
src/DataStruct/pushButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/pushButton.cpp.o
.PHONY : src/DataStruct/pushButton.cpp.o

src/DataStruct/pushButton.i: src/DataStruct/pushButton.cpp.i
.PHONY : src/DataStruct/pushButton.i

# target to preprocess a source file
src/DataStruct/pushButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/pushButton.cpp.i
.PHONY : src/DataStruct/pushButton.cpp.i

src/DataStruct/pushButton.s: src/DataStruct/pushButton.cpp.s
.PHONY : src/DataStruct/pushButton.s

# target to generate assembly for a file
src/DataStruct/pushButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/DataStruct/pushButton.cpp.s
.PHONY : src/DataStruct/pushButton.cpp.s

src/Networks/HTTP.o: src/Networks/HTTP.cpp.o
.PHONY : src/Networks/HTTP.o

# target to build an object file
src/Networks/HTTP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/HTTP.cpp.o
.PHONY : src/Networks/HTTP.cpp.o

src/Networks/HTTP.i: src/Networks/HTTP.cpp.i
.PHONY : src/Networks/HTTP.i

# target to preprocess a source file
src/Networks/HTTP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/HTTP.cpp.i
.PHONY : src/Networks/HTTP.cpp.i

src/Networks/HTTP.s: src/Networks/HTTP.cpp.s
.PHONY : src/Networks/HTTP.s

# target to generate assembly for a file
src/Networks/HTTP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/HTTP.cpp.s
.PHONY : src/Networks/HTTP.cpp.s

src/Networks/TCPWindow.o: src/Networks/TCPWindow.cpp.o
.PHONY : src/Networks/TCPWindow.o

# target to build an object file
src/Networks/TCPWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/TCPWindow.cpp.o
.PHONY : src/Networks/TCPWindow.cpp.o

src/Networks/TCPWindow.i: src/Networks/TCPWindow.cpp.i
.PHONY : src/Networks/TCPWindow.i

# target to preprocess a source file
src/Networks/TCPWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/TCPWindow.cpp.i
.PHONY : src/Networks/TCPWindow.cpp.i

src/Networks/TCPWindow.s: src/Networks/TCPWindow.cpp.s
.PHONY : src/Networks/TCPWindow.s

# target to generate assembly for a file
src/Networks/TCPWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/Networks/TCPWindow.cpp.s
.PHONY : src/Networks/TCPWindow.cpp.s

src/mainWindow.o: src/mainWindow.cpp.o
.PHONY : src/mainWindow.o

# target to build an object file
src/mainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/mainWindow.cpp.o
.PHONY : src/mainWindow.cpp.o

src/mainWindow.i: src/mainWindow.cpp.i
.PHONY : src/mainWindow.i

# target to preprocess a source file
src/mainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/mainWindow.cpp.i
.PHONY : src/mainWindow.cpp.i

src/mainWindow.s: src/mainWindow.cpp.s
.PHONY : src/mainWindow.s

# target to generate assembly for a file
src/mainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ComputerForQt.dir/build.make CMakeFiles/ComputerForQt.dir/src/mainWindow.cpp.s
.PHONY : src/mainWindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ComputerForQt_autogen"
	@echo "... ComputerForQt"
	@echo "... ComputerForQt_autogen/mocs_compilation.o"
	@echo "... ComputerForQt_autogen/mocs_compilation.i"
	@echo "... ComputerForQt_autogen/mocs_compilation.s"
	@echo "... src/DataStruct/ArrayList.o"
	@echo "... src/DataStruct/ArrayList.i"
	@echo "... src/DataStruct/ArrayList.s"
	@echo "... src/DataStruct/ArrayWindow.o"
	@echo "... src/DataStruct/ArrayWindow.i"
	@echo "... src/DataStruct/ArrayWindow.s"
	@echo "... src/DataStruct/DataTable.o"
	@echo "... src/DataStruct/DataTable.i"
	@echo "... src/DataStruct/DataTable.s"
	@echo "... src/DataStruct/LinkListWindow.o"
	@echo "... src/DataStruct/LinkListWindow.i"
	@echo "... src/DataStruct/LinkListWindow.s"
	@echo "... src/DataStruct/main.o"
	@echo "... src/DataStruct/main.i"
	@echo "... src/DataStruct/main.s"
	@echo "... src/DataStruct/pushButton.o"
	@echo "... src/DataStruct/pushButton.i"
	@echo "... src/DataStruct/pushButton.s"
	@echo "... src/Networks/HTTP.o"
	@echo "... src/Networks/HTTP.i"
	@echo "... src/Networks/HTTP.s"
	@echo "... src/Networks/TCPWindow.o"
	@echo "... src/Networks/TCPWindow.i"
	@echo "... src/Networks/TCPWindow.s"
	@echo "... src/mainWindow.o"
	@echo "... src/mainWindow.i"
	@echo "... src/mainWindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

